@echo off
set "BASE=C:\temp"
set "ROOT=%BASE%\schulung\aufgabe_2"

mkdir "%ROOT%"
mkdir "%ROOT%\ziel1"
mkdir "%ROOT%\ziel2"
mkdir "%ROOT%\alle"

mkdir "%ROOT%\ordner1"
mkdir "%ROOT%\ordner2"
mkdir "%ROOT%\ordner3"
mkdir "%ROOT%\ordner4"
mkdir "%ROOT%\ordner5"
mkdir "%ROOT%\ordner6"
mkdir "%ROOT%\ordner7"
mkdir "%ROOT%\ordner8"
mkdir "%ROOT%\ordner9"
mkdir "%ROOT%\ordner10"

type nul > "%ROOT%\ordner1\txt1.txt"
type nul > "%ROOT%\ordner1\word1.docx"
type nul > "%ROOT%\ordner1\txt2.txt"
type nul > "%ROOT%\ordner1\word2.docx"
type nul > "%ROOT%\ordner1\txt3.txt"
type nul > "%ROOT%\ordner1\word3.docx"
type nul > "%ROOT%\ordner1\txt4.txt"
type nul > "%ROOT%\ordner1\word4.docx"
type nul > "%ROOT%\ordner1\txt5.txt"
type nul > "%ROOT%\ordner1\word5.docx"

type nul > "%ROOT%\ordner2\txt6.txt"
type nul > "%ROOT%\ordner2\word6.docx"
type nul > "%ROOT%\ordner2\txt7.txt"
type nul > "%ROOT%\ordner2\word7.docx"
type nul > "%ROOT%\ordner2\txt8.txt"
type nul > "%ROOT%\ordner2\word8.docx"
type nul > "%ROOT%\ordner2\txt9.txt"
type nul > "%ROOT%\ordner2\word9.docx"
type nul > "%ROOT%\ordner2\txt10.txt"
type nul > "%ROOT%\ordner2\word10.docx"

type nul > "%ROOT%\ordner3\txt11.txt"
type nul > "%ROOT%\ordner3\word11.docx"
type nul > "%ROOT%\ordner3\txt12.txt"
type nul > "%ROOT%\ordner3\word12.docx"
type nul > "%ROOT%\ordner3\txt13.txt"
type nul > "%ROOT%\ordner3\word13.docx"
type nul > "%ROOT%\ordner3\txt14.txt"
type nul > "%ROOT%\ordner3\word14.docx"
type nul > "%ROOT%\ordner3\txt15.txt"
type nul > "%ROOT%\ordner3\word15.docx"

type nul > "%ROOT%\ordner4\txt16.txt"
type nul > "%ROOT%\ordner4\word16.docx"
type nul > "%ROOT%\ordner4\txt17.txt"
type nul > "%ROOT%\ordner4\word17.docx"
type nul > "%ROOT%\ordner4\txt18.txt"
type nul > "%ROOT%\ordner4\word18.docx"
type nul > "%ROOT%\ordner4\txt19.txt"
type nul > "%ROOT%\ordner4\word19.docx"
type nul > "%ROOT%\ordner4\txt20.txt"
type nul > "%ROOT%\ordner4\word20.docx"

type nul > "%ROOT%\ordner5\txt21.txt"
type nul > "%ROOT%\ordner5\word21.docx"
type nul > "%ROOT%\ordner5\txt22.txt"
type nul > "%ROOT%\ordner5\word22.docx"
type nul > "%ROOT%\ordner5\txt23.txt"
type nul > "%ROOT%\ordner5\word23.docx"
type nul > "%ROOT%\ordner5\txt24.txt"
type nul > "%ROOT%\ordner5\word24.docx"
type nul > "%ROOT%\ordner5\txt25.txt"
type nul > "%ROOT%\ordner5\word25.docx"

type nul > "%ROOT%\ordner6\txt26.txt"
type nul > "%ROOT%\ordner6\word26.docx"
type nul > "%ROOT%\ordner6\txt27.txt"
type nul > "%ROOT%\ordner6\word27.docx"
type nul > "%ROOT%\ordner6\txt28.txt"
type nul > "%ROOT%\ordner6\word28.docx"
type nul > "%ROOT%\ordner6\txt29.txt"
type nul > "%ROOT%\ordner6\word29.docx"
type nul > "%ROOT%\ordner6\txt30.txt"
type nul > "%ROOT%\ordner6\word30.docx"

type nul > "%ROOT%\ordner7\txt31.txt"
type nul > "%ROOT%\ordner7\word31.docx"
type nul > "%ROOT%\ordner7\txt32.txt"
type nul > "%ROOT%\ordner7\word32.docx"
type nul > "%ROOT%\ordner7\txt33.txt"
type nul > "%ROOT%\ordner7\word33.docx"
type nul > "%ROOT%\ordner7\txt34.txt"
type nul > "%ROOT%\ordner7\word34.docx"
type nul > "%ROOT%\ordner7\txt35.txt"
type nul > "%ROOT%\ordner7\word35.docx"

type nul > "%ROOT%\ordner8\txt36.txt"
type nul > "%ROOT%\ordner8\word36.docx"
type nul > "%ROOT%\ordner8\txt37.txt"
type nul > "%ROOT%\ordner8\word37.docx"
type nul > "%ROOT%\ordner8\txt38.txt"
type nul > "%ROOT%\ordner8\word38.docx"
type nul > "%ROOT%\ordner8\txt39.txt"
type nul > "%ROOT%\ordner8\word39.docx"
type nul > "%ROOT%\ordner8\txt40.txt"
type nul > "%ROOT%\ordner8\word40.docx"

type nul > "%ROOT%\ordner9\txt41.txt"
type nul > "%ROOT%\ordner9\word41.docx"
type nul > "%ROOT%\ordner9\txt42.txt"
type nul > "%ROOT%\ordner9\word42.docx"
type nul > "%ROOT%\ordner9\txt43.txt"
type nul > "%ROOT%\ordner9\word43.docx"
type nul > "%ROOT%\ordner9\txt44.txt"
type nul > "%ROOT%\ordner9\word44.docx"
type nul > "%ROOT%\ordner9\txt45.txt"
type nul > "%ROOT%\ordner9\word45.docx"

type nul > "%ROOT%\ordner10\txt46.txt"
type nul > "%ROOT%\ordner10\word46.docx"
type nul > "%ROOT%\ordner10\txt47.txt"
type nul > "%ROOT%\ordner10\word47.docx"
type nul > "%ROOT%\ordner10\txt48.txt"
type nul > "%ROOT%\ordner10\word48.docx"
type nul > "%ROOT%\ordner10\txt49.txt"
type nul > "%ROOT%\ordner10\word49.docx"
type nul > "%ROOT%\ordner10\txt50.txt"
type nul > "%ROOT%\ordner10\word50.docx"
